{% set name = "pysmartdl2" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pysmartdl2-{{ version }}.tar.gz
  sha256: 70238764afdf3775eb62284cbf53e7fd5afc2a1a78caf765273fb71e36fe4527

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - pysmartdl2
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/amkrajewski/pysmartdl2
  summary: Modernized fork of the Smart Download Manager for Python by iTaybb with CI testing matrix and other 2024 bells and whistles.
  license: Unlicense
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
