{% set name = "pysmartdl2" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pysmartdl2-{{ version }}.tar.gz
  sha256: 1a87a3f299f285852eec2507c57fea456808279a84a6a6fb87c8112c612373b8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - pysmartdl2
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/amkrajewski/pysmartdl2
  summary: Modernized fork of the Smart Download Manager for Python by iTaybb with CI testing matrix and other 2024 bells and whistles.
  license: Unlicense
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
